### ISSUE TITLE
能说一下怎么修改 背景图片的吗 在哪个文件啊

### ISSUE THREAD

**Issue by fffmath** [imaegoo/hexo-theme-icarus#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by imaegoo** [comment]
修改文件 `themes/icarus/source/css/imaegoo.styl`，搜索 body:before，将里面的 background 改成自己想要的背景图片 url。

**Comment by fffmath** [comment]
谢谢你 已经成功了



在 2020-07-09 09:25:24，"iMaeGoo" <notifications@github.com> 写道：

修改文件 themes/icarus/source/css/imaegoo.styl，搜索 body:before，将里面的 background 改成自己想要的背景图片 url。

**Comment by punksinatra** [comment]
> Modify the file `themes/icarus/source/css/imaegoo.styl`, search for body:before, and change the background inside to the url of the background image you want.

I do not have imaegoo.styl I only have night.styl

**Comment by imaegoo** [comment]
> I do not have imaegoo.styl I only have night.styl

@punksinatra You may use `night4` branch which does not have a background image. The file `themes/icarus/source/css/imaegoo.styl` is under `imaegoo4` branch, and `imaegoo4` is the persenal customization version of the Icarus theme for my website.

**Comment by punksinatra** [comment]
> > I do not have imaegoo.styl I only have night.styl
> 
> @punksinatra You may use `night4` branch which does not have a background image. The file `themes/icarus/source/css/imaegoo.styl` is under `imaegoo4` branch, and `imaegoo4` is the persenal customization version of the Icarus theme for my website.

Ok thank you again for your help
